[env]
# Config Files
KUBECONFIG = '{{config_root}}/kubeconfig'
TALOSCONFIG = '{{config_root}}/talosconfig'

[tools]
"aqua:helm/helm" = "3.19.2"
"aqua:helmfile/helmfile" = "1.1.9"
"pipx:flux-local" = "latest"
"uv" = "latest"
"talhelper" = "latest"
"talosctl" = "1.11.5"
