[env]
KUBECONFIG = "{{config_root}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = "{{config_root}}/talosconfig"
JUST_UNSTABLE = "1"

[tools]
"uv" = "latest"
"pipx:flux-local" = "latest"
talosctl = { version = "latest", exe = "talosctl" }
