[env]
KUBECONFIG = "{{config_root}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/talosconfig"
JUST_UNSTABLE = "1"

[tools]
"aqua:helm/helm" = "4.0.4"
"aqua:helmfile/helmfile" = "1.2.3"
"gum" = "latest"
"pipx:flux-local" = "latest"
"talosctl" = "1.11.6"
"uv" = "latest"
