[env]
# Config Files
KUBECONFIG = '{{config_root}}/kubeconfig'
TALOSCONFIG = '{{config_root}}/talosconfig'
# Included file paths
_.file = [
  "{{config_root}}/kubernetes/apps/system-upgrade/versions.env"
]

[tools]
"aqua:astral-sh/uv" = ["latest"]
helm = "3.19.2"
"pipx:flux-local" = ["8.0.0"]
talhelper = "latest"
talosctl = "1.11.5"
