---
ingress:
  - hostname: donoso.family
    service: https://ingress-nginx-controller.networking.svc.cluster.local:443
    originRequest:
      originServerName: ingress.donoso.family
  - hostname: "*.donoso.family"
    service: https://ingress-nginx-controller.networking.svc.cluster.local:443
    originRequest:
      originServerName: ingress.donoso.family
  - service: http_status:404
