---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: go2rtc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: go2rtc-secret
    template:
      data:
        go2rtc.yaml: |-
          log:
            streams: error # Prevent log spam from UniFi Protect
          api:
            listen: :80
            origin: "*"
          rtsp:
            listen: :554
          webrtc:
            listen: :8555
            candidates:
              - 192.168.69.124:8555
              - stun:8555
            ice_servers:
              - urls:
                  - stun:stun.cloudflare.com:3478
          streams:
            camera.backyard_fluent:
              - rtsp://{{ .RTSP_USERNAME }}:{{ .RTSP_PASSWORD }}@192.168.20.238
            camera.backyard_pool_fluent:
              - rtsp://{{ .RTSP_USERNAME }}:{{ .RTSP_PASSWORD }}@192.168.20.42
            camera.entrance_fluent:
              - rtsp://{{ .RTSP_USERNAME }}:{{ .RTSP_PASSWORD }}@192.168.20.223
            camera.living_room_fluent:
              - rtsp://{{ .RTSP_USERNAME }}:{{ .RTSP_PASSWORD }}@192.168.20.231
            camera.family_room_fluent:
              - rtsp://{{ .RTSP_USERNAME }}:{{ .RTSP_PASSWORD }}@192.168.20.84
            camera.service_yard_fluent:
              - rtsp://{{ .RTSP_USERNAME }}:{{ .RTSP_PASSWORD }}@192.168.20.146
  dataFrom:
    - extract:
        key: reolink
