---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - default
  - home
  - kube-system
  - kyverno
  - media
  - networking
  - rook-ceph
  - system-upgrade
  - security
  - volsync
